# Generated by Django 3.0.3 on 2020-02-25 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fco_database.lib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('i', 'Individual'), ('c', 'Couple'), ('h', 'Household')], default='i', max_length=1)),
                ('membership_expiry', models.DateField(blank=True, null=True)),
                ('working_expiry', models.DateField(blank=True, null=True)),
                ('membership_approved', models.BooleanField(default=False)),
                ('concession', models.BooleanField(default=False)),
                ('concession_proof', models.ImageField(blank=True, null=True, upload_to=fco_database.lib.RandomFileName('concession_images'))),
                ('ts_entered', models.DateTimeField(auto_now_add=True)),
                ('ts_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ts_entered', models.DateTimeField(auto_now_add=True)),
                ('ts_updated', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.Member')),
            ],
        ),
    ]
