# Generated by Django 3.0.3 on 2020-03-02 10:28

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import fco_database.lib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=9, null=True)),
                ('postcode', models.CharField(blank=True, max_length=4, null=True)),
                ('suburb', models.CharField(blank=True, max_length=32, null=True)),
                ('mailing_list', models.BooleanField(default=True)),
                ('volunteer_preferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('concession_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=32)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ts_entered', models.DateTimeField(auto_now_add=True)),
                ('ts_updated', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_expiry', models.DateField(blank=True, null=True)),
                ('working_expiry', models.DateField(blank=True, null=True)),
                ('concession', models.BooleanField(default=False)),
                ('concession_proof', models.ImageField(blank=True, null=True, upload_to=fco_database.lib.RandomFileName('concession_images'))),
                ('concession_type', models.CharField(blank=True, choices=[('s', 'Student'), ('p', 'Pension'), ('h', 'Healthcare'), ('o', 'Other')], max_length=1, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('membership_active', models.BooleanField(default=False)),
                ('ts_entered', models.DateTimeField(auto_now_add=True)),
                ('ts_updated', models.DateTimeField(auto_now=True)),
                ('membership_type', models.ForeignKey(on_delete=models.SET('OLD_MEMBERSHIP'), to='members.MembershipType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Membership'),
        ),
    ]
