# Generated by Django 3.0.3 on 2020-02-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='member_id',
            new_name='member',
        ),
    ]
