# Generated by Django 3.0.3 on 2020-02-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200225_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('i', 'Individual'), ('c', 'Couple'), ('h', 'Household'), ('p', 'Philanthropic')], default='i', max_length=1),
        ),
    ]
