# Generated by Django 3.0.3 on 2020-02-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200225_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mailing_list',
            field=models.BooleanField(default=True),
        ),
    ]
