# Generated by Django 3.0.3 on 2020-04-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200411_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='volunteer_options',
            new_name='volunteer_preferences',
        ),
    ]
