# Generated by Django 3.0.3 on 2020-04-15 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200411_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='entered_by',
        ),
        migrations.AlterField(
            model_name='shift',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
