# Generated by Django 3.0.3 on 2020-02-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_mailing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='concession_type',
            field=models.CharField(choices=[('i', 'Individual'), ('c', 'Couple'), ('h', 'Household'), ('p', 'Philanthropic')], default='i', max_length=1),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='postcode',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='suburb',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
