# Generated by Django 3.0.3 on 2020-02-27 12:16

import django.contrib.postgres.fields
from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200227_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=32)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='volunteer_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='concession_type',
            field=models.CharField(choices=[(members.models.Member.MembershipTypes['INDIVIDUAL'], 'Individual'), (members.models.Member.MembershipTypes['COUPLE'], 'Couple'), (members.models.Member.MembershipTypes['HOUSEHOLD'], 'Household'), (members.models.Member.MembershipTypes['PHIL'], 'Philanthropic')], default='i', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[(members.models.Member.MembershipTypes['INDIVIDUAL'], 'Individual'), (members.models.Member.MembershipTypes['COUPLE'], 'Couple'), (members.models.Member.MembershipTypes['HOUSEHOLD'], 'Household'), (members.models.Member.MembershipTypes['PHIL'], 'Philanthropic')], default='i', max_length=1),
        ),
    ]
