# Generated by Django 3.0.3 on 2020-08-08 14:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200415_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteeroption',
            name='code',
        ),
        migrations.AlterField(
            model_name='member',
            name='volunteer_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_active',
            field=models.BooleanField(default=False),
        ),
    ]
