# Generated by Django 3.0.3 on 2020-02-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200227_2316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolunteerOptions',
            new_name='VolunteerOption',
        ),
    ]
