# Generated by Django 3.0.3 on 2020-02-27 12:23

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200227_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='concession_type',
            field=models.CharField(blank=True, choices=[(members.models.Member.ConcessionTypes['STUDENT'], 'Student'), (members.models.Member.ConcessionTypes['PENSION'], 'Pension'), (members.models.Member.ConcessionTypes['HEALTHCARE'], 'Healthcare'), (members.models.Member.ConcessionTypes['OTHER'], 'Other')], max_length=1, null=True),
        ),
    ]
