# Generated by Django 3.0.3 on 2020-02-27 12:35

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20200227_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='concession_type',
            field=django_enum_choices.fields.EnumChoiceField(blank=True, choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Student', 'Student'), ('Pension', 'Pension'), ('Healthcare', 'Healthcare'), ('Other', 'Other')], enum_class=members.models.Member.ConcessionTypes, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Individual', 'Individual'), ('Couple', 'Couple'), ('Household', 'Household'), ('Philanthropic', 'Philanthropic')], enum_class=members.models.Member.MembershipTypes, max_length=13),
        ),
    ]
